# -*- coding: utf-8 -*-
"""Selenium&WebDrive.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nBEwfozmq-DYoyQ_8MklCMCS11HxPzc9

## selenium과 웹드라이버 설치
"""

!pip install selenium   # selenium 다운로드 설치
!pip install bs4        
!apt-get update         # 구글 드라이버 설치 위한 업데이트 필요
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver/usr/bin   # 설치한 구글드라이버를 /user/bin에다 복사

import sys    # sys를 import하고
sys.path.insert(0, '/user/lib/chromium-browser/chromedriver')    # 시스템path로 지정한다

# import sys
# sys.path.insert(0, '/user/lib/chromium-browser/chromedriver')

"""## 웹 드라이버 설정
* selenium을 일반 local에서 실행하면 브라우저가 뜬다.
colab에서는 브라우저를 띄워서 동작을 보지 않고 내부적으로만 작동시킴.
"""

from selenium import webdriver

chrome_options=webdriver.ChromeOptions()   # webdriver에 ChromeOptions()를 할당한다
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')   # 박스를 띄우지 않는다는 지정.
chrome_options.add_argument('--disable-dev-shm-usage')   # shm(shared memory)를 disable로 지정.

"""## 웹 드라이버 객체 생성
* 위에서 설정한 chrome_options을 주고 크롬 드라이버 객체를 생성
"""

driver=webdriver.Chrome('chromedriver', options=chrome_options)

"""## Selenium으로 사이트 실행 테스트"""

# get함수로 url(네이버 홈페이지)을 불러온다.
driver.get("https://www.naver.com/")